# Generated by Django 2.2 on 2021-07-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('short_term', models.CharField(max_length=255)),
                ('start_date', models.DateField(default='null')),
                ('target_date', models.DateField(default='null')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=25)),
                ('confirm', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('completed_task', models.BooleanField(default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_to_goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_for_goal', to='goal_app.Goal')),
                ('goal_setter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='made_goal', to='goal_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='goal',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_goal', to='goal_app.User'),
        ),
        migrations.AddField(
            model_name='goal',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks_for_goal', to='goal_app.User'),
        ),
    ]
