# Generated by Django 2.2 on 2021-07-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='completed_goal',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='completed_goal_date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_task_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
