# Generated by Django 2.2 on 2021-07-20 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0002_auto_20210719_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='tasks',
        ),
    ]
