# Generated by Django 2.2 on 2021-07-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0003_remove_goal_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='tasks',
            field=models.ManyToManyField(related_name='tasks_for_goal', to='goal_app.User'),
        ),
    ]
