# Generated by Django 2.2 on 2021-07-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0004_goal_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='completed_goal_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
