# Generated by Django 2.2 on 2021-07-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0005_auto_20210719_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='completed_goal_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
