# Generated by Django 2.2 on 2021-07-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0006_auto_20210719_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(),
        ),
    ]
