# Generated by Django 2.2 on 2021-07-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goal_app', '0007_auto_20210720_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateField(default='null'),
        ),
    ]
